### ISSUE TITLE
initial b28 support broken again.

### ISSUE THREAD

**Issue by zeffii** [zeffii/TubeTool#20]
API updates in BPY / operators have impacted TubeTool's functionality.  I will look at the operator closer, at present it is unusable in the latest b28 builds.

**Comment by zeffii** [comment]
https://github.com/zeffii/TubeTool/pull/21 

should work now. but I may return at a later stage to turn this into a modal operator.

**Comment by toomanydemons** [comment]
Any word on if/when this will be fixed and usable?

My brother and I have found this to be one of the most useful addons  ever made for modeling complex environments. It's genuinely painful not to have it working : (

**Comment by zeffii** [comment]
i pushed an update yesterday, should work in 2.80.

this version will not work in 2.79

**Comment by toomanydemons** [comment]
How strange, ok, then it must be something on my end.
Currently I can't enable the addon, though I can install it. I get this error message:
https://gyazo.com/80f00af4ff159daab0197b592378f09f

My version of Blender 2.8 was updated yesterday..

**Comment by toomanydemons** [comment]
Hmm how annoying! I just updated my version of Blender 2.8 to the current release (blender-2.80-0bbff8a71138-win64) and I still get an error mesh, even on a fresh install of the addon.

Unfortunately my python coding skills are only for power modelling and not making addons. Is there a cache somewhere that I need to delete to get this working?

Thanks. I really love and rely on your addon. It's second to none for speed when it comes to curves.

**Comment by zeffii** [comment]
ok! thanks I see what's happening now
```
Exception in module register(): C:\Users\zeffi\Desktop\scripts\addons_contrib\TubeTool\__init__.py
Traceback (most recent call last):
  File "C:\Users\zeffi\Desktop\test_blenders\blender-2.80-0bbff8a71138-win64\blender-2.80.0-git.0bbff8a71138-windows64\2.80\scripts\modules\addon_utils.py", line 384, in enable
    mod.register()
  File "C:\Users\zeffi\Desktop\scripts\addons_contrib\TubeTool\__init__.py", line 57, in register
    bpy.types.VIEW3D_MT_edit_mesh_specials.prepend(menu_func)
AttributeError: 'RNA_Types' object has no attribute 'VIEW3D_MT_edit_mesh_specials'

Exception in module register(): C:\Users\zeffi\Desktop\scripts\addons_contrib\TubeTool\__init__.py
Traceback (most recent call last):
  File "C:\Users\zeffi\Desktop\test_blenders\blender-2.80-0bbff8a71138-win64\blender-2.80.0-git.0bbff8a71138-windows64\2.80\scripts\modules\addon_utils.py", line 384, in enable
    mod.register()
  File "C:\Users\zeffi\Desktop\scripts\addons_contrib\TubeTool\__init__.py", line 56, in register
    tt_operators.register()
  File "C:\Users\zeffi\Desktop\test_blenders\blender-2.80-0bbff8a71138-win64\blender-2.80.0-git.0bbff8a71138-windows64\2.80\scripts\modules\bpy\utils\__init__.py", line 669, in register
    register_class(cls)
ValueError: register_class(...): already registered as a subclass
```
i'll fix that asap ( i needed to test in a newer Blender2.8 build.. )

**Comment by zeffii** [comment]
ok, it appears b28 devs renamed/removed a menu identifier/class 
```diff
- bpy.types.VIEW3D_MT_edit_mesh_specials
+ bpy.types.VIEW3D_MT_edit_mesh_context_menu
```

**Comment by zeffii** [comment]
if you download again, install .. it should behave better 
https://github.com/zeffii/TubeTool/commit/84994a38ce4b8e2550c7040d99e12ea30385bc58

**Comment by toomanydemons** [comment]
You are so awesome!! Thanks so much! :D

**Comment by toomanydemons** [comment]
One thing I've noticed that you are probably already aware of... It seems you can only create one curve with the addon. It has been this way since the first 0.0.4 release of Tube Tool. I have found ways around this limitation for the time being and have been keeping a close eye on the addon, since it's my favorite from Blender 2.7-series
 If you try to create a second curve, it re-allocates your curve to that new selection of squares. Also if you make the curve into a mesh, the addon no longer works unless you restart Blender, it just throws an error. 
https://gyazo.com/88aaf68fdbda57101cfa5bf856d51023
This also happens if you delete the curve.

Also the "to mesh" button throws an error right away in every case:
https://gyazo.com/968ccda3c7f92c7e6de84a604fecb1ac
The only way to get multiple curves in your project is to duplicate the curve every time you create a new one, so that when you run the addon again, it re-allocates your duplicated curve.
I've been keeping an eye on this addon for some time hoping that this gets worked out. I assume the current functionality is due to an incomplete API ?

**Comment by zeffii** [comment]
thanks for the detailed comment there, i'll address those issues soon.

rather than explaining the "why" i'm sure you'd much prefer if I just corrected the code, so.. keep an eye out for fixes (The b28 updates are coming faster..and i've been occupied with other things, it doesn't make sense to always be on top of the latest builds..)

no ETA. but it's on my radar again.

**Comment by zeffii** [comment]
track it here https://github.com/zeffii/TubeTool/issues/22
